name: Build Repository
on: [push]
jobs:
  Build-Repository:
    runs-on: ubuntu-latest
    steps:
      - name: Installing Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: npm -v

      - name: Check out repository code
        uses: actions/checkout@v2
        run: echo "Downloaded repository code"

      - name: Install Dependencies
        run: npm install

      - name: Building the application
        run: npm build
